from __future__ import annotations


# ============================================================
# Topic clusters
# ============================================================

TOPIC_KEYS: list[str] = [
    "computer_vision",
    "nlp",
    "time_series",
    "reinforcement_learning",
    "speech_audio",
    "gan",
    "classical_ml",
    "genetic_algorithms",
    "ai_project_management_custom_sales",
    "production_integration",
    "llm_agents",
    "automl",
    "data_engineering",
    "backend_development",
    "frontend_development",
    "fullstack_development",
    "devops_sre",
    "qa_engineering",
    "cybersecurity",
    "product_analytics",
    "product_management_it",
]

TOPIC_LABELS: dict[str, str] = {
    "computer_vision": "Computer Vision",
    "nlp": "NLP / Language AI",
    "time_series": "Time Series",
    "reinforcement_learning": "Reinforcement Learning",
    "speech_audio": "Speech / Audio AI",
    "gan": "GAN",
    "classical_ml": "Classical ML",
    "genetic_algorithms": "Genetic Algorithms",
    "ai_project_management_custom_sales": "AI Project Management / Custom AI Sales",
    "production_integration": "Production Integration / MLOps",
    "llm_agents": "LLM Agents",
    "automl": "AutoML",
    "data_engineering": "Data Engineering",
    "backend_development": "Backend Development",
    "frontend_development": "Frontend Development",
    "fullstack_development": "Fullstack Development",
    "devops_sre": "DevOps / SRE",
    "qa_engineering": "QA Engineering",
    "cybersecurity": "Cybersecurity",
    "product_analytics": "Product Analytics",
    "product_management_it": "Product / IT Management",
}

TOPIC_CLUSTER_RULES: dict[str, list[str]] = {
    "computer_vision": [
        "computer vision",
        "cv",
        "vision",
        "image recognition",
        "image classification",
        "object detection",
        "segmentation",
        "ocr",
        "оптическое распознавание",
        "компьютерное зрение",
        "распознавание изображений",
        "распознавание образов",
        "детекция объектов",
        "обработка изображений",
        "face recognition",
        "facial recognition",
        "video analytics",
    ],
    "nlp": [
        "nlp",
        "natural language processing",
        "llm prompting",
        "text mining",
        "text classification",
        "sentiment analysis",
        "named entity recognition",
        "ner",
        "machine translation",
        "qa system",
        "question answering",
        "chatbot",
        "обработка естественного языка",
        "обработка текста",
        "анализ текста",
        "анализ тональности",
        "классификация текста",
        "суммаризация",
        "извлечение сущностей",
        "llm",
        "bert",
        "gpt",
        "transformer",
        "transformers",
        "rag",
        "semantic search",
        "embeddings",
        "чат-бот",
        "чат бот",
        "языковая модель",
        "языковые модели",
    ],
    "time_series": [
        "time series",
        "forecasting",
        "demand forecasting",
        "series forecasting",
        "temporal modeling",
        "timeseries",
        "временные ряды",
        "прогнозирование",
        "прогноз спроса",
        "прогноз продаж",
        "forecast",
        "lstm forecasting",
        "ts analysis",
    ],
    "reinforcement_learning": [
        "reinforcement learning",
        "rl",
        "q-learning",
        "policy gradient",
        "dqn",
        "ppo",
        "bandits",
        "multi-armed bandit",
        "обучение с подкреплением",
        "марковские процессы",
        "агентное обучение",
    ],
    "speech_audio": [
        "speech recognition",
        "automatic speech recognition",
        "asr",
        "speech-to-text",
        "s2t",
        "audio processing",
        "speaker recognition",
        "voice recognition",
        "tts",
        "text-to-speech",
        "распознавание речи",
        "распознавание аудио",
        "обработка аудио",
        "голосовые интерфейсы",
        "speech analytics",
    ],
    "gan": [
        "gan",
        "gans",
        "generative adversarial network",
        "generative adversarial networks",
        "stylegan",
        "cyclegan",
        "pix2pix",
        "генеративно-состязательные сети",
        "генеративно состязательные сети",
        "состязательные сети",
    ],
    "classical_ml": [
        "machine learning",
        "classical ml",
        "ml",
        "supervised learning",
        "unsupervised learning",
        "classification",
        "regression",
        "clustering",
        "feature engineering",
        "xgboost",
        "lightgbm",
        "catboost",
        "random forest",
        "svm",
        "логистическая регрессия",
        "машинное обучение",
        "классическое машинное обучение",
        "обучение моделей",
        "классификация",
        "регрессия",
        "кластеризация",
        "machine_learning",
        "data science",
        "data scientist",
        "ml engineer",
        "machine learning engineer",
    ],
    "genetic_algorithms": [
        "genetic algorithm",
        "genetic algorithms",
        "evolutionary computation",
        "evolutionary algorithm",
        "neuroevolution",
        "genetic programming",
        "эволюционные алгоритмы",
        "генетические алгоритмы",
        "генетическое программирование",
    ],
    "ai_project_management_custom_sales": [
        "ai project management",
        "ml project management",
        "управление ai проектами",
        "управление ml проектами",
        "delivery management",
        "solution selling",
        "consultative selling",
        "enterprise ai sales",
        "pre-sale",
        "presale",
        "custom ai development",
        "заказная разработка",
        "продажи ai решений",
        "продажи на заказ",
        "enterprise ai consulting",
        "ai consulting",
        "ai_pm_sales",
    ],
    "production_integration": [
        "mlops",
        "llmops",
        "deployment",
        "deploy",
        "production",
        "production ai",
        "model serving",
        "inference",
        "monitoring",
        "observability",
        "feature store",
        "data pipeline",
        "ci/cd for ml",
        "docker for ml",
        "kubernetes for ml",
        "integration",
        "интеграция в production",
        "продакшн",
        "внедрение моделей",
        "развертывание моделей",
        "ml в production",
        "эксплуатация моделей",
    ],
    "llm_agents": [
        "llm agent",
        "llm agents",
        "ai agent",
        "ai agents",
        "agentic workflow",
        "multi-agent",
        "multi agent",
        "tool use",
        "function calling",
        "agent memory",
        "autonomous agent",
        "orchestrator",
        "crew ai",
        "langgraph",
        "autogen",
        "агенты на базе llm",
        "ai-агенты",
        "ии агенты",
        "агентные системы",
        "мультиагентные системы",
        "rag",
        "rag-бот",
        "rag бот",
        "rag-боты",
    ],
    "automl": [
        "automl",
        "auto ml",
        "automated machine learning",
        "automated ml",
        "hyperparameter optimization",
        "hpo",
        "neural architecture search",
        "nas",
        "feature search",
        "auto-sklearn",
        "autokeras",
        "автоматизированное машинное обучение",
        "автоматический подбор гиперпараметров",
        "автоматизация ml",
    ],
    "data_engineering": [
        "data engineering",
        "data engineer",
        "etl",
        "elt",
        "data warehouse",
        "dwh",
        "data lake",
        "data pipeline",
        "airflow",
        "spark",
        "hadoop",
        "kafka",
        "stream processing",
        "batch processing",
        "orchestration",
        "dbt",
        "sql engineering",
        "построение пайплайнов данных",
        "инженерия данных",
        "хранилище данных",
        "обработка данных",
        "big data",
        "bigdata",
        "большие данные",
        "clickhouse",
        "greenplum",
    ],
    "backend_development": [
        "backend",
        "back-end",
        "server-side",
        "api development",
        "rest api",
        "graphql api",
        "microservices",
        "django",
        "flask",
        "fastapi",
        "spring boot",
        "go backend",
        "node.js backend",
        "database design",
        "sqlalchemy",
        "orm",
        "бэкенд",
        "серверная разработка",
        "разработка api",
        "микросервисы",
    ],
    "frontend_development": [
        "frontend",
        "front-end",
        "react",
        "vue",
        "angular",
        "javascript ui",
        "typescript ui",
        "web interface",
        "html css javascript",
        "next.js",
        "nuxt",
        "верстка",
        "фронтенд",
        "пользовательский интерфейс",
        "разработка интерфейсов",
    ],
    "fullstack_development": [
        "fullstack",
        "full-stack",
        "full stack",
        "end-to-end web development",
        "web developer",
        "fullstack developer",
        "полный цикл веб-разработки",
        "фулстек",
    ],
    "devops_sre": [
        "devops",
        "sre",
        "site reliability engineering",
        "infrastructure",
        "terraform",
        "ansible",
        "docker",
        "kubernetes",
        "helm",
        "ci/cd",
        "continuous delivery",
        "platform engineering",
        "linux administration",
        "облачная инфраструктура",
        "инфраструктура",
        "девопс",
        "сопровождение production",
    ],
    "qa_engineering": [
        "qa",
        "quality assurance",
        "test automation",
        "automated testing",
        "selenium",
        "playwright",
        "cypress",
        "pytest",
        "postman testing",
        "manual testing",
        "нагрузочное тестирование",
        "тестирование",
        "автоматизация тестирования",
        "qa engineer",
    ],
    "cybersecurity": [
        "cybersecurity",
        "information security",
        "application security",
        "appsec",
        "network security",
        "soc",
        "siem",
        "penetration testing",
        "pentest",
        "secure coding",
        "devsecops",
        "безопасность",
        "информационная безопасность",
        "кибербезопасность",
        "защита приложений",
    ],
    "product_analytics": [
        "product analytics",
        "product analyst",
        "ab testing",
        "a/b testing",
        "experimentation",
        "sql analytics",
        "bi analytics",
        "дашборды",
        "dashboarding",
        "метрики продукта",
        "юнит-экономика",
        "продуктовая аналитика",
        "аналитика продукта",
        "аналитик данных",
        "data analytics",
        "data analyst",
        "визуализация данных",
        "data visualization",
        "tableau",
        "power bi",
        "datalens",
        "superset",
    ],
    "product_management_it": [
        "product management",
        "project management",
        "delivery management",
        "product owner",
        "scrum",
        "agile",
        "cto",
        "tech lead",
        "it management",
        "управление продуктом",
        "управление проектом",
        "руководитель команды",
        "технический менеджмент",
    ],
}

# Маппинг сырых ai_topics от market_agent на канонические TOPIC_KEYS.
# Используется на этапе классификации, когда upstream уже проставил теги,
# но они не совпадают с ключами таксономии.
RAW_AI_TOPIC_TO_CANONICAL: dict[str, list[str]] = {
    "artificial_intelligence": [
        "classical_ml",
        "nlp",
        "computer_vision",
        "llm_agents",
        "production_integration",
    ],
    "machine_learning": [
        "classical_ml",
    ],
    "deep_learning": [
        "classical_ml",
        "computer_vision",
        "nlp",
    ],
    "ai_pm_sales": [
        "ai_project_management_custom_sales",
    ],
    "data_science": [
        "classical_ml",
        "product_analytics",
        "data_engineering",
    ],
    "data_engineering": [
        "data_engineering",
    ],
    "analytics": [
        "product_analytics",
    ],
    "python": [
        "backend_development",
        "data_engineering",
        "classical_ml",
    ],
    "sql": [
        "data_engineering",
        "product_analytics",
    ],
}


# ============================================================
# Audiences
# ============================================================

AUDIENCE_RULES: dict[str, list[str]] = {
    "beginners": [
        "beginner",
        "начинающих",
        "с нуля",
        "no-code",
        "без опыта",
        "intro",
        "introduction",
        "beginners",
        "начинающие",
    ],
    "career_switchers": [
        "career switch",
        "career transition",
        "смена профессии",
        "новая профессия",
        "войти в профессию",
        "войти в it",
        "войти в ai",
        "переквалификация",
    ],
    "junior_specialists": [
        "junior",
        "junior specialist",
        "junior engineer",
        "junior analyst",
        "старт в профессии",
        "начинающий специалист",
        "младший специалист",
    ],
    "working_professionals": [
        "for professionals",
        "working professionals",
        "for practitioners",
        "для практиков",
        "для работающих специалистов",
        "повышение квалификации",
        "upskill",
        "reskill",
        "professionals",
        "профессионалы",
    ],
    "senior_experts": [
        "advanced",
        "senior",
        "lead",
        "expert track",
        "экспертный уровень",
        "senior-уровень",
        "для опытных специалистов",
    ],
    "managers_leads": [
        "team lead",
        "tech lead",
        "руководитель",
        "лид",
        "leadership",
        "управление командой",
        "руководители и лиды",
        "managers",
        "менеджеры",
    ],
    "students": [
        "student",
        "students",
        "студент",
        "студенты",
        "для студентов",
    ],
    "corporate_teams": [
        "corporate team",
        "teams",
        "for teams",
        "команды",
        "командное обучение",
        "обучение команд",
    ],
    "experienced_engineers": [
        "experienced engineers",
        "experienced developers",
        "production engineers",
        "industrial engineers",
        "опытные инженеры",
        "для инженеров",
        "engineering track",
    ],
    "corporate_clients": [
        "corporate",
        "enterprise",
        "b2b",
        "для компаний",
        "корпоративный",
        "in-company",
    ],
    "managers_and_execs": [
        "manager",
        "product owner",
        "cto",
        "ceo",
        "руководитель",
        "менеджер",
        "управление",
        "executive",
    ],
}


# ============================================================
# Value props
# ============================================================

VALUE_PROP_RULES: dict[str, list[str]] = {
    "job_outcome": [
        "career",
        "job",
        "employment",
        "трудоустройство",
        "карьера",
        "career track",
    ],
    "project_based": [
        "project",
        "portfolio",
        "capstone",
        "pet project",
        "проект",
        "портфолио",
        "кейсы",
    ],
    "mentor_support": [
        "mentor",
        "mentoring",
        "куратор",
        "наставник",
        "обратная связь",
        "code review",
    ],
    "certificate": [
        "certificate",
        "certification",
        "сертификат",
        "удостоверение",
        "диплом",
    ],
    "academic_depth": [
        "research",
        "theory",
        "математика",
        "научный",
        "академический",
        "университет",
        "formal methods",
        "fundamentals",
    ],
    "short_intensive": [
        "intensive",
        "bootcamp",
        "sprint",
        "интенсив",
        "boot camp",
    ],
    "custom_training": [
        "custom",
        "tailored",
        "bespoke",
        "под заказ",
        "кастомный",
        "индивидуальный трек",
    ],
    "b2b_enablement": [
        "b2b",
        "enterprise",
        "корпоративный",
        "для компании",
        "командное обучение",
    ],
    "production_readiness": [
        "production",
        "deployment",
        "serving",
        "mlops",
        "llmops",
        "monitoring",
        "industrial",
    ],
    "llm_agent_readiness": [
        "agent",
        "agents",
        "tool use",
        "multi-agent",
        "langgraph",
        "autogen",
        "crew ai",
    ],
}


# ============================================================
# Format signals
# ============================================================

FORMAT_SIGNAL_RULES: dict[str, list[str]] = {
    "cohort": [
        "cohort",
        "group learning",
        "группа",
        "поток",
        "с преподавателем",
    ],
    "self_paced": [
        "self-paced",
        "self paced",
        "в своем темпе",
        "asynchronous",
        "recorded lessons",
    ],
    "hybrid": [
        "hybrid",
        "blended",
        "смешанный формат",
        "live + recorded",
    ],
    "enterprise_delivery": [
        "corporate",
        "enterprise",
        "b2b",
        "for teams",
        "для компаний",
        "in-company",
    ],
}


# ============================================================
# Core signals
# Canonical learning / differentiation axes
# Exactly aligned with report_builder.CANONICAL_CORE_SIGNAL_ORDER
# ============================================================

CORE_SIGNAL_KEYS: list[str] = [
    "independent_assignments",
    "flexible_schedule",
    "webinars_and_free_content",
    "job_support",
    "job_guarantee",
    "ai_content_base",
    "ai_specialization",
    "real_enterprise_projects",
    "own_ai_hr_agency",
    "course_buyout_employment",
    "hackathon_wins",
    "ai_reality_format",
    "ai_curator_chatgpt",
    "lessons_count",
]

CORE_SIGNAL_LABELS: dict[str, str] = {
    "independent_assignments": "Independent Assignments",
    "flexible_schedule": "Flexible Schedule",
    "webinars_and_free_content": "Webinars and Free Content",
    "job_support": "Job Support",
    "job_guarantee": "Job Guarantee",
    "ai_content_base": "AI Content Base",
    "ai_specialization": "AI Specialization",
    "real_enterprise_projects": "Real Enterprise Projects",
    "own_ai_hr_agency": "Own AI HR Agency",
    "course_buyout_employment": "Course Buyout / Employment",
    "hackathon_wins": "Hackathon Wins",
    "ai_reality_format": "AI Reality Format",
    "ai_curator_chatgpt": "AI Curator ChatGPT",
    "lessons_count": "Lessons Count / Content Volume",
}

CORE_SIGNAL_RULES: dict[str, list[str]] = {
    "independent_assignments": [
        "самостоятельные задания",
        "самостоятельная работа",
        "домашние задания",
        "домашняя работа",
        "практические задания",
        "задания для самостоятельной работы",
        "homework",
        "assignments",
        "independent assignments",
        "self-study tasks",
        "practical exercises",
        "take-home tasks",
    ],
    "flexible_schedule": [
        "гибкий график",
        "гибкое расписание",
        "в удобное время",
        "в своем темпе",
        "свободный график",
        "можно совмещать с работой",
        "удобный график",
        "flexible schedule",
        "learn at your own pace",
        "self-paced",
        "asynchronous",
        "on your own schedule",
        "study anytime",
    ],
    "webinars_and_free_content": [
        "вебинары",
        "бесплатные вебинары",
        "открытые вебинары",
        "бесплатный контент",
        "бесплатные материалы",
        "открытые уроки",
        "вводные уроки",
        "webinars",
        "free webinars",
        "free content",
        "open lessons",
        "open webinars",
        "free materials",
        "free workshops",
    ],
    "job_support": [
        "карьерная поддержка",
        "карьерный центр",
        "помощь с резюме",
        "подготовка к собеседованию",
        "карьерная консультация",
        "поддержка в поиске работы",
        "career support",
        "career services",
        "resume review",
        "interview prep",
        "job search support",
        "career coaching",
        "employment support",
        "job assistance",
    ],
    "job_guarantee": [
        "гарантия трудоустройства",
        "трудоустройство гарантировано",
        "гарантируем работу",
        "вернем деньги если не найдете работу",
        "job guarantee",
        "employment guarantee",
        "guaranteed job",
        "money-back job guarantee",
        "guaranteed placement",
    ],
    "ai_content_base": [
        "база знаний по ai",
        "ai база знаний",
        "библиотека материалов по ai",
        "база ai-материалов",
        "архив материалов по ai",
        "knowledge base",
        "ai knowledge base",
        "content library",
        "learning library",
        "resource base",
        "materials archive",
    ],
    "ai_specialization": [
        "специализация по ai",
        "специализация в ai",
        "ai специализация",
        "ai track",
        "трек по искусственному интеллекту",
        "специализированная программа по ai",
        "ai specialization",
        "specialization in ai",
        "generative ai specialization",
        "llm specialization",
    ],
    "real_enterprise_projects": [
        "реальные проекты",
        "enterprise проекты",
        "проекты для компаний",
        "боевые проекты",
        "реальные кейсы компаний",
        "корпоративные кейсы",
        "real enterprise projects",
        "real-world enterprise projects",
        "client projects",
        "enterprise case studies",
        "production cases",
    ],
    "own_ai_hr_agency": [
        "собственное hr-агентство",
        "собственное ai hr агентство",
        "внутреннее hr агентство",
        "hr-агентство школы",
        "ai hr agency",
        "own hr agency",
        "internal recruiting agency",
        "internal ai recruiting",
        "talent agency",
    ],
    "course_buyout_employment": [
        "выкуп курса работодателем",
        "обучение с выкупом курса",
        "курс оплачивает работодатель",
        "трудоустройство через выкуп курса",
        "course buyout",
        "employer-sponsored buyout",
        "employment with course buyout",
        "employer pays for the course",
    ],
    "hackathon_wins": [
        "победы в хакатонах",
        "призовые места в хакатонах",
        "выигрывают хакатоны",
        "хакатоны",
        "hackathon wins",
        "hackathon победы",
        "award-winning hackathon teams",
        "hackathon champions",
        "hackathon awards",
    ],
    "ai_reality_format": [
        "ai reality",
        "ai reality format",
        "реалити-формат",
        "реалити формат",
        "формат реалити",
        "обучение в реалити-формате",
        "show-style cohort",
        "reality-based learning format",
    ],
    "ai_curator_chatgpt": [
        "ai-куратор",
        "ии-куратор",
        "chatgpt-куратор",
        "куратор на базе chatgpt",
        "ai curator",
        "chatgpt curator",
        "gpt curator",
        "ai assistant curator",
        "llm curator",
    ],
    "lessons_count": [
        "количество занятий",
        "количество уроков",
        "число занятий",
        "объём курса",
        "объем курса",
        "количество модулей",
        "число модулей",
        "lessons count",
        "number of lessons",
        "course volume",
        "content volume",
        "modules count",
        "total lessons",
        "total hours",
    ],
}


# ============================================================
# Competency families
# ============================================================

COMPETENCY_FAMILY_RULES: dict[str, list[str]] = {
    "ai_ml_core": [
        "machine learning",
        "ml",
        "machine learning engineer",
        "ml engineer",
        "data science",
        "data scientist",
        "deep learning",
        "нейронные сети",
        "машинное обучение",
        "data scientist junior",
    ],
    "generative_ai": [
        "llm",
        "gpt",
        "rag",
        "agent",
        "agents",
        "ai agent",
        "llm agent",
        "prompt engineering",
        "genai",
        "generative ai",
        "генеративный ии",
        "ai-агенты",
        "искусственный интеллект",
        "artificial intelligence",
    ],
    "ai_in_production": [
        "mlops",
        "llmops",
        "deployment",
        "model serving",
        "monitoring",
        "feature store",
        "inference",
        "production ai",
        "продакшн",
        "внедрение моделей",
    ],
    "data_platforms": [
        "data engineering",
        "data pipeline",
        "etl",
        "elt",
        "airflow",
        "spark",
        "kafka",
        "dbt",
        "data warehouse",
        "dwh",
        "инженерия данных",
    ],
    "software_engineering": [
        "backend",
        "frontend",
        "fullstack",
        "api development",
        "microservices",
        "django",
        "flask",
        "fastapi",
        "react",
        "vue",
        "angular",
        "web development",
        "веб-разработка",
        "разработка api",
    ],
    "cloud_devops": [
        "devops",
        "sre",
        "docker",
        "kubernetes",
        "terraform",
        "ci/cd",
        "cloud",
        "инфраструктура",
        "девопс",
        "platform engineering",
    ],
    "quality_security": [
        "qa",
        "testing",
        "test automation",
        "selenium",
        "playwright",
        "cybersecurity",
        "information security",
        "appsec",
        "pentest",
        "информационная безопасность",
        "тестирование",
    ],
    "analytics_bi": [
        "analytics",
        "bi",
        "dashboard",
        "sql analytics",
        "product analytics",
        "a/b testing",
        "experimentation",
        "дашборды",
        "аналитика",
        "продуктовая аналитика",
    ],
    "product_delivery_management": [
        "product management",
        "project management",
        "delivery management",
        "product owner",
        "scrum",
        "agile",
        "cto",
        "tech lead",
        "управление продуктом",
        "управление проектом",
        "руководитель",
    ],
    "enterprise_enablement": [
        "b2b",
        "enterprise",
        "corporate",
        "custom training",
        "consulting",
        "presale",
        "solution selling",
        "для компаний",
        "корпоративный",
        "заказная разработка",
    ],
}

COMPETENCY_FAMILY_LABELS: dict[str, str] = {
    "ai_ml_core": "AI / ML Core",
    "generative_ai": "Generative AI",
    "ai_in_production": "AI in Production",
    "data_platforms": "Data Platforms",
    "software_engineering": "Software Engineering",
    "cloud_devops": "Cloud / DevOps",
    "quality_security": "Quality / Security",
    "analytics_bi": "Analytics / BI",
    "product_delivery_management": "Product / Delivery Management",
    "enterprise_enablement": "Enterprise Enablement",
}


# ============================================================
# Unified registry for rule-driven classification
# ============================================================

ALL_RULE_GROUPS: dict[str, dict[str, list[str]]] = {
    "topic_clusters": TOPIC_CLUSTER_RULES,
    "audiences": AUDIENCE_RULES,
    "value_props": VALUE_PROP_RULES,
    "format_signals": FORMAT_SIGNAL_RULES,
    "core_signals": CORE_SIGNAL_RULES,
    "competency_families": COMPETENCY_FAMILY_RULES,
}